Algoritmo "ContadorDeEstrela"

Var
   star: inteiro
   i: caractere

Inicio



   enquanto(i <> "N") Faca
      Escreval("Você está vendo uma estrela? ")
      leia(i)

      Se(i = "S" ou "s")entao
         Escreval("Opa, uma estrela!")
         star <- star + 1
      senao
         se(i = "N") ou (i = "N")
            Escreval("A quantidade total de estrela é, ", star)
         fimse
      fimse
   fimenquanto

Fimalgoritmo